---
collections:

    # Ansible Community General Collection
    # This collection has a few dependencies that will result in downloading other collections
    # https://github.com/ansible-collections/community.general
    # NOTE: nmap plugin broken starting at v2.5.2 https://github.com/ansible-collections/community.general/issues/2512
    - name: community.general
      version: 2.5.1
